### PR TITLE
Edited Page for MenuItemReview plus tests and stories 

### LINKED ISSUE #42: Edit Page for `MenuItemReview` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for MenuItemReview
* Form Component for MenuItemReview  
* Copy Placeholders for `MenuItemReview` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [x] When the user navigates to `/menuitemreview/edit/:id` where `:id` 
      is the `id` field of a valid record in the table, the page will be populated
      with data from that row of the database, and will be able to edit fields
      from that database record.

- [x] Valid changes made on the page are saved to the database when the user clicks
      the submit button.
- [x] Changes made on the page are NOT saved when the page contains invalid data; instead,
      appropriate error messages are shown.
- [x] Changes made on the page are NOT saved when the user clicks the cancel button,
      and the user is routed back to the previous page they were on (like the "back button").     

- [x] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new page (since this is a frontend change).

- [x] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `MenuItemReviewEditPage` component.

# Implementation Details

- [x] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `MenuItemReview` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `MenuItemReview`, but not identical.  You will need
      to know the exact name of the API endpoints for `MenuItemReview` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [x] Replace the placeholder content in `MenuItemReviewEditPage.js`
      with appropriate content from `RestaurantEditPage.js` and/or
      `UCSBDatesEditPage.js`. Be sure to get the API endpoint names correct for your `MenuItemReview` table.

- [x] Replace the placeholder content in `MenuItemReviewEditPage.test.js`
      with appropriate content from `RestaurantEditPage.test.js` and/or
      `UCSBDatesEditPage.test.js`. Be sure to get the API endpoint names correct for your `MenuItemReview` table.

- [x] Under `frontend/src/stories/pages/MenuItemReview/` create a file
      called `MenuItemReviewEditPage.stories.js` modelled after 
      the files `RestaurantEditPage.stories.js` and/or `UCSBDatesEditPage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/MenuItemReview/MenuItemReviewEditPage.js`

# What to do next

When you are done with this issue, you are finished with the frontend CRUD
operations for `MenuItemReview`.  Now, please give your full attention to 
helping others on your team to complete the sprint, so that the team
is ready to submit on Canvas by the deadline.

### PR DESCRIPTION
**Pull request by bella-ward**
This PR adds Edit page and tests for MenuItemReview as well as storybook. 
Screenshot: 
Screenshot 2023-11-09 at 4 20 54 PM

dokky deployement: https://team03-bella-ward-dev.dokku-07.cs.ucsb.edu

Closes #42

### CODE REVIEW

**Review by erica-ll — APPROVED** [review]
LGMT, Ill try to fix the merge conflict for the other one.

**Comment by bella-ward** [comment]
Closing this to make a new PR with same branch, but to fix the merge conflicts, cuz i cant fix remotely.

**Comment by bella-ward** [comment]
Not sure how to fix this, if i do it remotely I don't have the main branch changes, so I can't fix the merge conflict, but not sure if its ok to pull main .

**Comment by midnightzada** [comment]
I think we should merge this pr, then create a new pr to fix the conflicts.

**Pull request merged**
